# XBox 360 wired controller
joy_teleop:
  ros__parameters:
    piloting:
      type: topic
      message_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: []  # No deadman buttons
      axis_mappings:
        -
          axis: 4  # Right thumb (up/down)
          target: linear.x
          scale: 0.4
          offset: 0.0
        -
          axis: 3  # Right thumb stick (left/right)
          target: angular.z
          scale: 2.5
          offset: 0.0
